routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use App\Http\Controllers\Admin\BrandController;

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('admin/home', [App\Http\Controllers\HomeController::class, 'adminHome'])->name('admin.home')->middleware('is_admin');


Route::group([
    'prefix' => 'admin',
], function () {
    Route::group(['middleware' => ['auth']], function() {
		Route::resource('brands',BrandController::class);
    });
});

app/Models/Brand.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Brand extends Model
{
    use HasFactory;

    protected $fillable = [
        'name', 'description'
    ];
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'is_admin',
        'code',
        'refer_code',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Admin/BrandController.php
<?php
  
namespace App\Http\Controllers\Admin;
   
use App\Http\Controllers\Controller;
use App\Models\Brand;
use Illuminate\Http\Request;
  
class BrandController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $brands = Brand::latest()->paginate(10);
        return view('admin.brand.index',compact('brands'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }
     
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.brand.create');
    }
    
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|max:150',
            'description' => 'required',
        ]);
    
        Brand::create($request->all());
     
        return redirect()->route('brands.index')
                        ->with('success','Brand created successfully.');
    }
     
     
    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $brand = Brand::find($id);
        return view('admin.brand.edit',compact('brand'));
    }
    
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required|max:150',
            'description' => 'required',
        ]);

        $input = $request->all();
        $brand = Brand::find($id);
        $brand->update($input);

        return redirect()->route('brands.index')
                        ->with('success','Brand updated successfully');
    }
    
    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Brand::find($id)->delete();
        return redirect()->route('brands.index')
                        ->with('success','Brand deleted successfully');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function adminHome()
    {
        return view('adminHome');
    }
}

resources/views/admin/brand/create.blade.php
@extends('layouts.admin')
   
@section('content')
@if ($message = Session::get('success'))
<div class="alert alert-success">
    <ul class="margin-bottom-none padding-left-lg">
        <li>{{ $message }}</li>
    </ul>
</div>
@endif
@if ($errors->any())
<div class="alert alert-danger">
    <strong>Whoops!</strong> There were some problems with your input.<br><br>
    <ul>
    @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
    @endforeach
    </ul>
</div>
@endif
<div class="container-fluid page__heading-container">
    <div class="page__heading d-flex align-items-center">
        <div class="flex">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb mb-0">
                    <li class="breadcrumb-item"><a href="#"><i class="material-icons icon-20pt">home</i></a></li>
                    <li class="breadcrumb-item">Pages</li>
                    <li class="breadcrumb-item" aria-current="page"><a href="{{ url('admin/brands') }}">Brand</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Create</li>
                </ol>
            </nav>
            <h1 class="m-0">Create Brand</h1>
        </div>
    </div>
</div>
<div class="row no-gutters" style="padding:25px;">
    <div class="col-lg-12 card-form__body card-body">
        <form method="post" action="{{ route('brands.store') }}" enctype="multipart/form-data">
        @csrf
            <div class="form-group">
                <label for="exampleInputEmail1">Name:</label>
                <input type="text" name="name" class="form-control" id="exampleInputEmail1" placeholder="Enter Brand Name.." required>
            </div>
            <div class="form-group">
                <label for="exampleInputPassword1">Description:</label>
                <textarea class="form-control" name="description" rows="10" id="description" placeholder="Enter Description.." required></textarea>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
            <a class="btn btn-warning" href="{{ url('admin/brands') }}">Back</a>
        </form>
    </div>
</div>
@endsection

resources/views/admin/brand/edit.blade.php
@extends('layouts.admin')
   
@section('content')
@if ($message = Session::get('success'))
<div class="alert alert-success">
    <ul class="margin-bottom-none padding-left-lg">
        <li>{{ $message }}</li>
    </ul>
</div>
@endif
@if ($errors->any())
<div class="alert alert-danger">
    <strong>Whoops!</strong> There were some problems with your input.<br><br>
    <ul>
    @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
    @endforeach
    </ul>
</div>
@endif
<div class="container-fluid page__heading-container">
    <div class="page__heading d-flex align-items-center">
        <div class="flex">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb mb-0">
                    <li class="breadcrumb-item"><a href="#"><i class="material-icons icon-20pt">home</i></a></li>
                    <li class="breadcrumb-item">Pages</li>
                    <li class="breadcrumb-item" aria-current="page"><a href="{{ url('admin/brands') }}">Brand</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Edit</li>
                </ol>
            </nav>
            <h1 class="m-0">Edit Brand</h1>
        </div>
    </div>
</div>
<div class="row no-gutters" style="padding:25px;">
    <div class="col-lg-12 card-form__body card-body">
        <form method="post" action="{{ route('brands.update', $brand->id) }}" enctype="multipart/form-data">
        @csrf
        @method('PATCH')
            <div class="form-group">
                <label for="exampleInputEmail1">Name:</label>
                <input type="text" name="name" class="form-control" id="exampleInputEmail1" required value="{{$brand->name}}">
            </div>
            <div class="form-group">
                <label for="exampleInputPassword1">Description:</label>
                <textarea class="form-control" name="description" rows="10" id="description" required>{{$brand->description}}</textarea>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
            <a class="btn btn-warning" href="{{ url('admin/brands') }}">Back</a>
        </form>
    </div>
</div>
@endsection

resources/views/admin/brand/index.blade.php
@extends('layouts.admin')
   
@section('content')
<div class="container-fluid page__heading-container">
    <div class="page__heading d-flex align-items-center">
        <div class="flex">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb mb-0">
                    <li class="breadcrumb-item"><a href="#"><i class="material-icons icon-20pt">home</i></a></li>
                    <li class="breadcrumb-item">Pages</li>
                    <li class="breadcrumb-item active" aria-current="page">Brand</li>
                </ol>
            </nav>
            <h1 class="m-0">Brands</h1>
        </div>
        <a href="{{ route('brands.create') }}" class="btn btn-success ml-3">Create <i class="material-icons">add</i></a>
    </div>
</div>
@if ($message = Session::get('success'))
<div class="alert alert-success">
    <ul class="margin-bottom-none padding-left-lg">
        <li>{{ $message }}</li>
    </ul>
</div>
@endif
@if ($message = Session::get('error'))
<div class="alert alert-danger">
    <ul class="margin-bottom-none padding-left-lg">
        <li>{{ $message }} </li>
    </ul>
</div>
@endif
<div class="row no-gutters" style="padding:25px;">
    <div class="col-lg-12 card-form__body">

        <table class="table mb-0 thead-border-top-0" id="datatable">
            <thead>
                <tr class="text-center">
                    <th>Brand name</th>
                    <th>Description</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
            @foreach ($brands as $key => $brand)
            <tr>
                <td>{{ $brand->name }}</td>
                <td>{{ $brand->description }} </td>
                <td class="text-center">
                    <a class="btn btn-primary btn-sm" href="{{ route('brands.edit',$brand->id) }}"  title="Edit"><i class="fas fa-edit"></i></a>
                    <form method="post" action="{{ route('brands.destroy',$brand->id) }}" style='display:inline' >
                    @csrf
                    @method('DELETE')
                    <button type="submit"  onclick="return confirm('Are you sure to Delete the Brand?');" class="btn btn-danger btn-sm"  title="Delete" ><i class="fas fa-trash"></i></button>
                    </form>
                </td>
            </tr>
            @endforeach
            </tbody>
        </table>

    </div>
</div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')
   
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>
                <div class="card-body">
                    You are normal user.
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/admin.blade.php
<!DOCTYPE html>
<html lang="en"
      dir="ltr">

    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible"
              content="IE=edge">
        <meta name="viewport"
              content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>Dashboard</title>

        <!-- Prevent the demo from appearing in search engines -->
        <meta name="robots"
              content="noindex">

        <!-- Perfect Scrollbar -->
        <link type="text/css"
              href="{{ asset('/assets/vendor/perfect-scrollbar.css') }}"
              rel="stylesheet">

        <!-- App CSS -->
        <link type="text/css"
              href="{{ asset('/assets/css/app.css') }}"
              rel="stylesheet">
        <link type="text/css"
              href="{{ asset('/assets/css/app.rtl.css') }}"
              rel="stylesheet">

        <!-- Material Design Icons -->
        <link type="text/css"
              href="{{ asset('/assets/css/vendor-material-icons.css') }}"
              rel="stylesheet">
        <link type="text/css"
              href="{{ asset('/assets/css/vendor-material-icons.rtl.css') }}"
              rel="stylesheet">

        <!-- Font Awesome FREE Icons -->
        <link type="text/css"
              href="{{ asset('/assets/css/vendor-fontawesome-free.css') }}"
              rel="stylesheet">
        <link type="text/css"
              href="{{ asset('/assets/css/vendor-fontawesome-free.rtl.css') }}"
              rel="stylesheet">

        <link rel="stylesheet" href="{{ asset('/plugins/datatable/dataTables.bootstrap4.css') }}">

        <!-- Global site tag (gtag.js) - Google Analytics -->
        <script async
                src="https://www.googletagmanager.com/gtag/js?id=UA-133433427-1"></script>
        <script>
            window.dataLayer = window.dataLayer || [];

            function gtag() {
                dataLayer.push(arguments);
            }
            gtag('js', new Date());
            gtag('config', 'UA-133433427-1');
        </script>

        <!-- Flatpickr -->
        <link type="text/css"
              href="{{ asset('/assets/css/vendor-flatpickr.css') }}"
              rel="stylesheet">
        <link type="text/css"
              href="{{ asset('/assets/css/vendor-flatpickr.rtl.css') }}"
              rel="stylesheet">
        <link type="text/css"
              href="{{ asset('/assets/css/vendor-flatpickr-airbnb.css') }}"
              rel="stylesheet">
        <link type="text/css"
              href="{{ asset('/assets/css/vendor-flatpickr-airbnb.rtl.css') }}"
              rel="stylesheet">

        <!-- Vector Maps -->
        <link type="text/css"
              href="{{ asset('/assets/vendor/jqvmap/jqvmap.min.css') }}"
              rel="stylesheet">
        @yield('css')  
    </head>

    <body class="layout-default">

        <div class="preloader"></div>

        <!-- Header Layout -->
        <div class="mdk-header-layout js-mdk-header-layout">

            <!-- Header -->

            @include('layouts.header')

            <!-- // END Header -->

            <!-- Header Layout Content -->
            <div class="mdk-header-layout__content">

                <div class="mdk-drawer-layout js-mdk-drawer-layout" data-pushdata-responsive-width="992px">
                    <div class="mdk-drawer-layout__content page">

                        @yield('content')

                    </div>
                    <!-- // END drawer-layout__content -->

                    @include('layouts.sidebar')

                    
                </div>
                <!-- // END drawer-layout -->

            </div>
            <!-- // END header-layout__content -->

        </div>
        <!-- // END header-layout -->

        <div id="app-settings">
            <app-settings layout-active="default"></app-settings>
        </div>

        <!-- jQuery -->
        <script src="{{ asset('/assets/vendor/jquery.min.js') }}"></script>

        <!-- Bootstrap -->
        <script src="{{ asset('/assets/vendor/popper.min.js') }}"></script>
        <script src="{{ asset('/assets/vendor/bootstrap.min.js') }}"></script>

        <!-- Perfect Scrollbar -->
        <script src="{{ asset('/assets/vendor/perfect-scrollbar.min.js') }}"></script>

        <!-- DOM Factory -->
        <script src="{{ asset('/assets/vendor/dom-factory.js') }}"></script>

        <!-- MDK -->
        <script src="{{ asset('/assets/vendor/material-design-kit.js') }}"></script>

        <!-- App -->
        <script src="{{ asset('/assets/js/toggle-check-all.js') }}"></script>
        <script src="{{ asset('/assets/js/check-selected-row.js') }}"></script>
        <script src="{{ asset('/assets/js/dropdown.js') }}"></script>
        <script src="{{ asset('/assets/js/sidebar-mini.js') }}"></script>
        <script src="{{ asset('/assets/js/app.js') }}"></script>

        <!-- App Settings (safe to remove) -->
        <script src="{{ asset('/assets/js/app-settings.js') }}"></script>

        <!-- Flatpickr -->
        <script src="{{ asset('/assets/vendor/flatpickr/flatpickr.min.js') }}"></script>
        <script src="{{ asset('/assets/js/flatpickr.js') }}"></script>

        <!-- Global Settings -->
        <script src="{{ asset('/assets/js/settings.js') }}"></script>

        <!-- Moment.js -->
        <script src="{{ asset('/assets/vendor/moment.min.js') }}"></script>
        <script src="{{ asset('/assets/vendor/moment-range.js') }}"></script>

        <!-- Chart.js -->
        <script src="{{ asset('/assets/vendor/Chart.min.js') }}"></script>

        <!-- App Charts JS -->
        <script src="{{ asset('/assets/js/charts.js') }}"></script>
        <script src="{{ asset('/assets/js/chartjs-rounded-bar.js') }}"></script>

        <!-- Chart Samples -->
        <script src="{{ asset('/assets/js/page.dashboard.js') }}"></script>
        <script src="assets/js/progress-charts.js') }}"></script>

        <!-- Vector Maps -->
        <script src="{{ asset('/assets/vendor/jqvmap/jquery.vmap.min.js') }}"></script>
        <script src="assets/vendor/jqvmap/maps/jquery.vmap.world.js') }}"></script>
        <script src="{{ asset('/assets/js/vector-maps.js') }}"></script>

        <script type="text/javascript" src="{{ asset('/plugins/datatable/jquery.dataTables.js') }}"></script> 
        <script type="text/javascript" src="{{ asset('/plugins/datatable/dataTables.bootstrap4.js') }}"></script> 
        @yield('js')  

        <script>
        $(document).ready(function() {
            $('#datatable').DataTable({
                  'paging'      : true,
                  'lengthChange': true,
                  'searching'   : true,
                  'ordering'    : true,
                  'info'        : true,
                  'autoWidth'   : true
            });
        });  
        </script>
    </body>
</html>

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>Drive4Free</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    Drive4Free
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif

                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">                               
                                {{ Auth::user()->name }}                               
                                <a href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                                {{ __('Logout') }}
                                </a>
                                <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                    @csrf
                                </form>                               
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/sidebar.blade.php
<div class="mdk-drawer  js-mdk-drawer"
                         id="default-drawer"
                         data-align="start">
                        <div class="mdk-drawer__content">
                            <div class="sidebar sidebar-light sidebar-left sidebar-p-t"
                                 data-perfect-scrollbar>
                                <div class="sidebar-heading" style="color:white;">Menu</div>
                                <ul class="sidebar-menu">
                                    <li class="sidebar-menu-item {{ in_array(Request::segment(2),array('brands')) ? 'open' : null }}">
                                        <a class="sidebar-menu-button"
                                           data-toggle="collapse"
                                           href="#pages_menu">
                                            <i class="sidebar-menu-icon sidebar-menu-icon--left material-icons">description</i>
                                            <span class="sidebar-menu-text">Pages</span>
                                            <span class="ml-auto sidebar-menu-toggle-icon"></span>
                                        </a>
                                        <ul class="sidebar-submenu collapse"
                                            id="pages_menu">
                                            <li class="sidebar-menu-item {{ in_array(Request::segment(2),array('brands')) ? 'active' : null }}">
                                                <a class="sidebar-menu-button"
                                                   href="{{ url('admin/brands') }}">
                                                    <span class="sidebar-menu-text">Brands</span>
                                                </a>
                                            </li>
                                            <li class="sidebar-menu-item">
                                                <a class="sidebar-menu-button"
                                                   href="#">
                                                    <span class="sidebar-menu-text">Cars</span>
                                                </a>
                                            </li>
                                        </ul>
                                    </li>
                                </ul>
                                <div class="sidebar-heading" style="color:white;">Components</div>
                                <div class="sidebar-block p-0 mb-0">
                                </div>

                            </div>
                        </div>
                    </div>